
import {
  collection, doc, addDoc, getDocs, getDoc,
  updateDoc, serverTimestamp, query,
  where, orderBy, onSnapshot, Unsubscribe
} from 'firebase/firestore';
import { db } from '../firebase/config';

export interface Appointment {
  id?: string;
  patientId: string;
  patientName: string;
  hospitalId: string;
  hospitalName: string;
  reason: string;
  status: 'waiting' | 'in-progress' | 'done' | 'cancelled';
  queuePosition: number;
  estimatedWaitMinutes: number;
  createdAt?: any;
  triage?: {
    severity: 'low' | 'moderate' | 'high' | 'critical' | 'clinical';
    triageCategory: string;
    patientSummary: string;
    chiefComplaint: string;
    recommendedScreenings: string[];
    recommendedActions: string[];
    urgency: 'routine' | 'within-24h' | 'immediate';
    patientAge?: number;
    patientGender?: string;
  };
  acceptedBy?: {
    id: string;
    name: string;
  };
}

const AVG_CONSULT_MINUTES = 15;

export const bookAppointment = async (
  patientId: string,
  patientName: string,
  hospitalId: string,
  hospitalName: string,
  reason: string,
  triage?: Appointment['triage'],
  travelTimeMinutes: number = 0
): Promise<Appointment> => {

  const queueRef = collection(db, 'appointments');
  const queueQuery = query(
    queueRef,
    where('hospitalId', '==', hospitalId),
    where('status', '==', 'waiting')
  );
  const snapshot = await getDocs(queueQuery);
  const currentQueueLength = snapshot.docs.length;
  const queuePosition = currentQueueLength + 1;
  const estimatedWaitMinutes = (queuePosition * AVG_CONSULT_MINUTES) + travelTimeMinutes;

  const appointment: Omit<Appointment, 'id'> = {
    patientId,
    patientName,
    hospitalId,
    hospitalName,
    reason,
    status: 'waiting',
    queuePosition,
    estimatedWaitMinutes,
    createdAt: serverTimestamp(),
    triage,
  };

  const docRef = await addDoc(collection(db, 'appointments'), appointment);
  return { ...appointment, id: docRef.id };
};

export const subscribeToPatientQueue = (
  patientId: string,
  onUpdate: (appointments: Appointment[]) => void
): Unsubscribe => {
  const q = query(
    collection(db, 'appointments'),
    where('patientId', '==', patientId),
    where('status', 'in', ['waiting', 'in-progress', 'done'])
  );

  return onSnapshot(q, (snapshot) => {
    const appointments = snapshot.docs.map(d => ({
      id: d.id,
      ...d.data()
    } as Appointment));

    appointments.sort((a, b) => {
      const timeA = a.createdAt?.seconds || 0;
      const timeB = b.createdAt?.seconds || 0;
      return timeB - timeA;
    });
    
    onUpdate(appointments);
  });
};

export const subscribeToHospitalQueue = (
  hospitalId: string,
  onUpdate: (appointments: Appointment[]) => void
): Unsubscribe => {
  const q = query(
    collection(db, 'appointments'),
    where('hospitalId', '==', hospitalId),
    where('status', 'in', ['waiting', 'in-progress'])
  );

  return onSnapshot(q, (snapshot) => {
    const appointments = snapshot.docs.map(d => ({
      id: d.id,
      ...d.data()
    } as Appointment));

    appointments.sort((a, b) => a.queuePosition - b.queuePosition);
    
    onUpdate(appointments);
  });
};

export const updateAppointmentStatus = async (
  appointmentId: string,
  status: Appointment['status']
) => {
  const ref = doc(db, 'appointments', appointmentId);
  await updateDoc(ref, { status });
};

export const acceptAppointment = async (
  appointmentId: string,
  doctorId: string,
  doctorName: string
) => {
  const ref = doc(db, 'appointments', appointmentId);
  const snap = await getDoc(ref);
  
  if (!snap.exists()) throw new Error("Appointment not found");
  const appointment = snap.data() as Appointment;

  await updateDoc(ref, {
    status: 'in-progress',
    acceptedBy: {
      id: doctorId,
      name: doctorName
    }
  });

  if (appointment.triage) {

    const chatId = `${appointment.patientId}_${doctorId}`;
    const t = appointment.triage;
    
    try {
      await addDoc(collection(db, 'chats', chatId, 'messages'), {
        text: `🏥 CLINICAL BRIEF: ${t.triageCategory.toUpperCase()}\n\nChief Complaint: ${t.chiefComplaint}\n\nSummary: ${t.patientSummary}\n\nRecommended Actions: ${t.recommendedActions.join(", ")}\n\n(Generated by Botsogo AI)`,
        senderId: "system_ai",
        createdAt: serverTimestamp()
      });
    } catch (err) {
      console.warn("Could not post brief to chat:", err);
    }
  }
};

export const getActiveAppointmentSession = async (patientId: string, doctorId: string): Promise<Appointment | null> => {
  const q = query(
    collection(db, 'appointments'),
    where('patientId', '==', patientId),
    where('status', '==', 'in-progress'),
    where('acceptedBy.id', '==', doctorId)
  );
  
  const snap = await getDocs(q);
  if (snap.empty) return null;
  return { id: snap.docs[0].id, ...snap.docs[0].data() } as Appointment;
};

export const resolveConsultation = async (appointmentId: string) => {
  const ref = doc(db, 'appointments', appointmentId);
  const snap = await getDoc(ref);
  if (!snap.exists()) return;
  const appointment = snap.data() as Appointment;

  await updateDoc(ref, {
    status: 'done',
    resolvedAt: serverTimestamp()
  });

  const recordRef = doc(collection(db, 'medical_records'));
  await addDoc(collection(db, 'medical_records'), {
    patientId: appointment.patientId,
    doctorId: appointment.acceptedBy?.id,
    doctorName: appointment.acceptedBy?.name || 'Doctor',
    date: serverTimestamp(),
    type: 'consultation',
    diagnosis: 'Consultation Completed',
    details: {
      appointmentId: appointmentId,
      reason: appointment.reason,
      summary: appointment.triage?.patientSummary || 'Regular consultation completed.'
    },
    createdAt: serverTimestamp()
  });
};

export const getPatientMedicalRecords = async (patientId: string) => {
  const q = query(
    collection(db, 'medical_records'),
    where('patientId', '==', patientId)
  );
  const snap = await getDocs(q);
  const records = snap.docs.map(d => ({ id: d.id, ...d.data() as any }));

  records.sort((a, b) => {
    const timeA = a.createdAt?.seconds || 0;
    const timeB = b.createdAt?.seconds || 0;
    return timeB - timeA;
  });
  
  return records;
};
